# Index ile elemanlara erişme

In [1]:
import numpy as np

In [2]:
a=np.random.randint(10,size=10)

In [3]:
a

array([8, 2, 5, 7, 5, 4, 2, 7, 5, 3])

In [8]:
a[0]

8

In [6]:
a[-1]

3

In [9]:
a[0]=100

In [10]:
a

array([100,   2,   5,   7,   5,   4,   2,   7,   5,   3])

In [11]:
m=np.random.randint(10,size=(3,5))

In [12]:
m

array([[0, 0, 1, 6, 9],
       [9, 1, 0, 6, 0],
       [6, 6, 1, 8, 0]])

In [13]:
m[0,0]

0

In [15]:
m[1,3]

6

In [16]:
m[2,3]=99

In [17]:
m

array([[ 0,  0,  1,  6,  9],
       [ 9,  1,  0,  6,  0],
       [ 6,  6,  1, 99,  0]])

In [18]:
m[1,1]=2.3

In [19]:
m

array([[ 0,  0,  1,  6,  9],
       [ 9,  2,  0,  6,  0],
       [ 6,  6,  1, 99,  0]])

**ondalıklı kesimi keserek ekler. int array içine sadece int float içine sadece float değer ekler.**

# Alt küme işlemi -- Slicing

In [20]:
sa=np.arange(20,30)

In [21]:
sa

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [22]:
sa[0:3]

array([20, 21, 22])

In [23]:
sa[2:]

array([22, 23, 24, 25, 26, 27, 28, 29])

In [24]:
sa[4:7]

array([24, 25, 26])

In [25]:
sa[:5]

array([20, 21, 22, 23, 24])

In [26]:
sa[0::3]

array([20, 23, 26, 29])

## iki boyutlu slice işlemleri

In [28]:
mm=np.random.randint(10,size=(5,5))

In [29]:
mm

array([[1, 7, 0, 1, 3],
       [9, 1, 4, 7, 6],
       [6, 2, 1, 4, 2],
       [8, 9, 5, 0, 9],
       [2, 7, 3, 0, 1]])

In [30]:
mm[:,2:3]

array([[0],
       [4],
       [1],
       [5],
       [3]])

In [32]:
mm[1:4,0:2]

array([[9, 1],
       [6, 2],
       [8, 9]])

In [33]:
mm[0]

array([1, 7, 0, 1, 3])

In [34]:
mm[:,3]

array([1, 7, 4, 0, 0])

# Alt küme üzerinde işlem yapmak

In [1]:
import numpy as np

In [2]:
a=np.random.randint(10,size=(5,5))

In [3]:
a

array([[9, 2, 0, 2, 2],
       [0, 7, 2, 9, 8],
       [5, 8, 9, 5, 4],
       [0, 8, 0, 0, 4],
       [5, 5, 1, 6, 8]])

In [4]:
alt_a=a[0:3,0:2]

In [5]:
alt_a

array([[9, 2],
       [0, 7],
       [5, 8]])

In [6]:
alt_a[0,0]=9999
alt_a[1,1]=888

In [7]:
alt_a

array([[9999,    2],
       [   0,  888],
       [   5,    8]])

In [8]:
a

array([[9999,    2,    0,    2,    2],
       [   0,  888,    2,    9,    8],
       [   5,    8,    9,    5,    4],
       [   0,    8,    0,    0,    4],
       [   5,    5,    1,    6,    8]])

In [9]:
m=np.random.randint(10,size=(5,5))

In [10]:
m

array([[8, 9, 1, 6, 4],
       [7, 2, 3, 0, 4],
       [6, 4, 2, 1, 3],
       [2, 0, 4, 0, 5],
       [8, 3, 6, 6, 9]])

In [13]:
alt_b=m[0:3,0:2].copy()
alt_b

array([[8, 9],
       [7, 2],
       [6, 4]])

In [14]:
alt_b[0:1]=100

In [15]:
alt_b

array([[100, 100],
       [  7,   2],
       [  6,   4]])

In [16]:
m

array([[8, 9, 1, 6, 4],
       [7, 2, 3, 0, 4],
       [6, 4, 2, 1, 3],
       [2, 0, 4, 0, 5],
       [8, 3, 6, 6, 9]])

# Fancy Index ile Elemanlara Erişmek (**önemli**)

In [17]:
v=np.arange(0,30,3)

In [18]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [19]:
v[1]

3

In [21]:
[v[1],v[3],v[5]]

[3, 9, 15]

In [22]:
al_getir=[1,3,5]

In [23]:
v[al_getir]

array([ 3,  9, 15])

## iki boyutta fancy oluşturma

In [24]:
mm=np.arange(9).reshape((3,3))

In [25]:
mm

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [26]:
satir=np.array([0,1])

In [27]:
sutun=np.array([1,2])

In [28]:
mm[satir,sutun]

array([1, 5])

## basit index ile fancy index

In [29]:
mm

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [30]:
m[0,[1,2]]

array([9, 1])

## slice ile fancy

In [31]:
m[0:,[1,2]]

array([[9, 1],
       [2, 3],
       [4, 2],
       [0, 4],
       [3, 6]])

# Koşullu eleman işlemleri

In [32]:
bb=np.array([1,2,3,4,5])

In [33]:
bb>5

array([False, False, False, False, False])

In [34]:
bb<3

array([ True,  True, False, False, False])

In [35]:
bb==4

array([False, False, False,  True, False])

In [36]:
bb[bb<3]

array([1, 2])

In [38]:
bb[bb>=3]

array([3, 4, 5])

In [39]:
bb*2

array([ 2,  4,  6,  8, 10])

In [40]:
bb**3

array([  1,   8,  27,  64, 125], dtype=int32)

# matematiksel işlemler

In [41]:
import numpy as np

In [42]:
g=np.array([1,2,3,4,5])

In [43]:
g*2

array([ 2,  4,  6,  8, 10])

## ufunc

In [44]:
np.subtract(v,1)

array([-1,  2,  5,  8, 11, 14, 17, 20, 23, 26])

In [45]:
np.subtract(g,3)

array([-2, -1,  0,  1,  2])

In [54]:
np.add(v,4)

array([ 4,  7, 10, 13, 16, 19, 22, 25, 28, 31])

In [47]:
np.add(g,4)

array([5, 6, 7, 8, 9])

In [48]:
np.multiply(g,3)

array([ 3,  6,  9, 12, 15])

In [50]:
np.sqrt(g)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [52]:
np.divide(g,5)

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [53]:
np.power(g,3)

array([  1,   8,  27,  64, 125], dtype=int32)

In [55]:
np. mod(g,2)

array([1, 0, 1, 0, 1], dtype=int32)

In [56]:
np.absolute(g)

array([1, 2, 3, 4, 5])

In [57]:
np.sin(g)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [58]:
?np

Type:        module
String form: <module 'numpy' from 'D:\\Users\\ercan\\anaconda31\\lib\\site-packages\\numpy\\__init__.py'>
File:        d:\users\ercan\anaconda31\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>>

# numpy ile iki bilinmeyenli denklem çözmek

In [59]:
import numpy as np

5*x0+x1=12
x0+3*x1=10

In [60]:
a=np.array([[5,1],[1,3]])
b=np.array([12,10])

In [61]:
a
b

array([12, 10])

In [62]:
a

array([[5, 1],
       [1, 3]])

In [63]:
x=np.linalg.solve(a,b)

In [64]:
x

array([1.85714286, 2.71428571])