# Pandas seri oluşturma işlemi

In [1]:
import pandas as pd

In [2]:
pd.Series([1,2,3,4,5])

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [3]:
seri=pd.Series([1,2,3,4,5])

In [4]:
type(seri)

pandas.core.series.Series

In [5]:
seri.axes

[RangeIndex(start=0, stop=5, step=1)]

In [6]:
seri.size

5

In [7]:
seri.ndim

1

In [8]:
seri[2]

3

In [9]:
seri.values

array([1, 2, 3, 4, 5], dtype=int64)

In [10]:
seri.value_counts

<bound method IndexOpsMixin.value_counts of 0    1
1    2
2    3
3    4
4    5
dtype: int64>

In [11]:
seri.head(3)

0    1
1    2
2    3
dtype: int64

In [12]:
seri.tail(3)

2    3
3    4
4    5
dtype: int64

## index isimlendirmesi

In [13]:
pd.Series([99,22,332,95,5])

0     99
1     22
2    332
3     95
4      5
dtype: int64

In [22]:
pd.Series([99,22,332,95,5], index=[1,3,5,7,9])

1     99
3     22
5    332
7     95
9      5
dtype: int64

In [25]:
seri=pd.Series([99,22,332,95,5], index=["a","b","c","d","e"])

In [26]:
seri["a"]

99

# Eleman işlemleri

In [2]:
import pandas as pd

In [3]:
import numpy as np

In [4]:
a=np.array([1,2,3,4,5])
seri=pd.Series(a)
seri

0    1
1    2
2    3
3    4
4    5
dtype: int32

In [5]:
seri[0]

1

In [6]:
seri[2:4]

2    3
3    4
dtype: int32

In [7]:
seri = pd.Series([121,200,150,99], index =["reg","loj","cart","rf"])

In [8]:
seri

reg     121
loj     200
cart    150
rf       99
dtype: int64

In [9]:
seri.index

Index(['reg', 'loj', 'cart', 'rf'], dtype='object')

In [10]:
seri.keys

<bound method Series.keys of reg     121
loj     200
cart    150
rf       99
dtype: int64>

In [12]:
list(seri.items())

[('reg', 121), ('loj', 200), ('cart', 150), ('rf', 99)]

In [13]:
seri.values

array([121, 200, 150,  99], dtype=int64)

## eleman sorgulama

In [14]:
"reg" in seri

True

In [15]:
121 in seri

False

In [16]:
seri["reg"]

121

## fancy eleman

In [17]:
seri[["rf","reg"]]

rf      99
reg    121
dtype: int64

In [18]:
seri["reg"]=130

In [19]:
seri

reg     130
loj     200
cart    150
rf       99
dtype: int64

In [20]:
seri["reg":"loj"]

reg    130
loj    200
dtype: int64

# PANDAS dataframe oluşturma

In [21]:
import pandas as pd

In [22]:
import numpy as np

In [23]:
l=[1,2,49,67,90]

In [25]:
pd.DataFrame(l,columns=["degisken_ismi"])

degisken_ismi
0              1
1              2
2             49
3             67
4             90

In [26]:
m=np.arange(1,10).reshape((3,3))

In [27]:
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
pd.DataFrame(m,columns=["var1","var2","var3"])

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

## Dataframe isimlendirme

In [29]:
df=pd.DataFrame(m,columns=["var1","var2","var3"])

In [30]:
df.head()

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [32]:
df.columns

Index(['var1', 'var2', 'var3'], dtype='object')

In [33]:
df.columns=["degisken1","degisken2","degisken3"]

In [34]:
df

degisken1  degisken2  degisken3
0          1          2          3
1          4          5          6
2          7          8          9

In [35]:
df.index=["row1","row2","row3"]

In [36]:
df

degisken1  degisken2  degisken3
row1          1          2          3
row2          4          5          6
row3          7          8          9

In [37]:
type(df)

pandas.core.frame.DataFrame

In [38]:
df.axes

[Index(['row1', 'row2', 'row3'], dtype='object'),
 Index(['degisken1', 'degisken2', 'degisken3'], dtype='object')]

In [39]:
df.shape

(3, 3)

In [40]:
df.ndim

2

In [41]:
df.size

9

In [42]:
df.values

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
type(df.values)

numpy.ndarray

In [44]:
df.head()

degisken1  degisken2  degisken3
row1          1          2          3
row2          4          5          6
row3          7          8          9

In [45]:
df.tail()

degisken1  degisken2  degisken3
row1          1          2          3
row2          4          5          6
row3          7          8          9

In [46]:
a=np.array([1,2,3,4,5])

In [48]:
pd.DataFrame(a,columns=["deg1"])

deg1
0     1
1     2
2     3
3     4
4     5