In [9]:
a=[1,2,3,4]
b=[2,3,4,5]

In [10]:
ab=[]

for i in range(0,len(a)):
    ab.append(a[i]*b[i])
              
ab

[2, 6, 12, 20]

In [14]:
import numpy as np

In [15]:
a=np.array([1,2,3,4])
b=np.array([2,3,4,5])

In [16]:
a*b

array([ 2,  6, 12, 20])

# Array Oluşturma

In [18]:
import numpy as np

In [19]:
a=np.array([1,2,3,4,5])

In [20]:
type(a)

numpy.ndarray

In [21]:
np.array([3.14,4,2,13])

array([ 3.14,  4.  ,  2.  , 13.  ])

##numpy her array içindeki veriyi direkt olarak tek tip değer yapıyor yukarıdakilerin hepsini float yaptı

#sıfırdan array oluşturma

In [23]:
np.zeros((3,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [25]:
np.ones((3,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [26]:
np.full((2,4),4)

array([[4, 4, 4, 4],
       [4, 4, 4, 4]])

In [29]:
np.arange(0,31, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [30]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [31]:
np.random.normal(10,4,(3,4))

array([[13.99372513, 20.20810163,  8.19978508, 14.39171087],
       [13.06271667, 17.10096696,  9.67022302,  7.18005035],
       [ 3.89009606, 17.54139433, 17.57245154, 11.22943222]])

In [32]:
np.random.randint(0,10,(3,3))

array([[9, 8, 2],
       [1, 7, 2],
       [3, 0, 5]])

# Array Özellikleri

* **ndim** : Boyut sayısı
* **shape** : Boyut bilgisi
* **size** : toplam eleman sayısı
* **dtype** : array veri tipi

In [1]:
import numpy as np

In [2]:
np.random.randint(10,size=10)

array([9, 2, 5, 1, 1, 4, 5, 6, 7, 9])

In [3]:
a=np.random.randint(10,size=10)

In [4]:
a.ndim

1

In [5]:
a.shape

(10,)

In [6]:
a.size

10

In [7]:
a.dtype

dtype('int32')

In [8]:
b=np.random.randint(10,size=(3,5))

In [9]:
b.ndim

2

In [10]:
b.shape

(3, 5)

In [11]:
b.size

15

In [12]:
b.dtype

dtype('int32')

# Yeniden Şekillendirme

In [13]:
import numpy as np

In [15]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
a=np.arange(1,10)

In [18]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
a.ndim

1

In [22]:
b=a.reshape((1,9))

In [23]:
b.ndim

2

# Array Birleştirme -- Concatenation

In [24]:
import numpy as np

In [25]:
x=np.array([1,2,3])
y=np.array([4,5,6])

In [26]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [27]:
z=np.array([7,8,9])

In [28]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## iki boyutlu yapma

In [30]:
a=np.array([[1,2,3],[4,5,6]])

In [33]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [34]:
np.concatenate([a,a],axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [35]:
np.concatenate([a,a],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

# Array Ayırma --Splitting

In [36]:
import numpy as np

In [41]:
x = np.array=([1,2,3,99,99,3,2,1])

In [43]:
x

[1, 2, 3, 99, 99, 3, 2, 1]

In [45]:
np.split(x,[3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

## elemanlara ayırırken atama yapmak

In [46]:
a,b,c=np.split(x,[3,5])

In [47]:
a

array([1, 2, 3])

In [48]:
b

array([99, 99])

In [49]:
c

array([3, 2, 1])

## iki boyutlu ayırma

In [51]:
m=np.arange(16).reshape(4,4)

In [52]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [53]:
np.vsplit(m,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [54]:
ust,alt=np.vsplit(m,[2])

In [55]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [56]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [57]:
np.hsplit(m,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [58]:
sol, sağ=np.hsplit(m,[2])

In [59]:
sol

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [60]:
sağ

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

# Sıralama -- Sorting

In [65]:
v=np.array=([2,1,4,3,5])

In [66]:
v

[2, 1, 4, 3, 5]

In [67]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [68]:
v

[2, 1, 4, 3, 5]

In [69]:
v.sort()

In [70]:
v

[1, 2, 3, 4, 5]

**v sort yazımında veri seti yeniden oluşturulur. np içinden çağırılırsa veri setine dokunmadan sıralama yapar**

## iki boyutlu sıralama

In [72]:
m=np.random.normal(20,5,(3,3))

In [73]:
m

array([[22.70733585, 29.37985098, 11.15791563],
       [19.63279846, 23.83553172, 26.70377353],
       [22.65733814, 27.96117047, 18.50195181]])

In [74]:
np.sort(m,axis=1)

array([[11.15791563, 22.70733585, 29.37985098],
       [19.63279846, 23.83553172, 26.70377353],
       [18.50195181, 22.65733814, 27.96117047]])

In [75]:
np.sort(m,axis=0)

array([[19.63279846, 23.83553172, 11.15791563],
       [22.65733814, 27.96117047, 18.50195181],
       [22.70733585, 29.37985098, 26.70377353]])